// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHymcePO1-5Qwai9U3UQrHv5h3O2nV9IE',
    appId: '1:657981533567:web:b54ac96ae40313749bbe4a',
    messagingSenderId: '657981533567',
    projectId: 'opensoureceproject',
    authDomain: 'opensoureceproject.firebaseapp.com',
    storageBucket: 'opensoureceproject.appspot.com',
    measurementId: 'G-VD00NVLTMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU9vLWzNlLU8_yUJ_x40WannISdgPK7cU',
    appId: '1:657981533567:android:0573c77d9686a2089bbe4a',
    messagingSenderId: '657981533567',
    projectId: 'opensoureceproject',
    storageBucket: 'opensoureceproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6NYvWcOToI1cDr9o_tWYmdDZW9jLmfXY',
    appId: '1:657981533567:ios:a70414693452cf559bbe4a',
    messagingSenderId: '657981533567',
    projectId: 'opensoureceproject',
    storageBucket: 'opensoureceproject.appspot.com',
    iosClientId: '657981533567-8i1tjmvo3qaea96fj7mens1vdmahk3qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceToFaceMessagerApp',
  );
}
